#!/usr/bin/env python3
"""Build data/pairs/agentic-ai-survey.jsonl.

The pair set is authored here rather than hand-written as JSON so the prose
stays readable and reviewable in diffs.  Every record pins the sha256 of the
corpus it was generated against; if the corpus changes, `--check` fails loudly
rather than letting stale outputs drift out of sync with their input.
"""
import argparse
import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORPUS = ROOT / "data" / "corpus" / "agentic-ai-survey.md"
OUT = ROOT / "data" / "pairs" / "agentic-ai-survey.jsonl"

# ---------------------------------------------------------------------------
# Each pair is (target_prompt, output).  `target_prompt` is the instruction the
# system must recover; it is never shown to the producer.  `output` was
# generated by running that prompt against the full corpus.
# `gold_sections` records which parts of the document the output actually drew
# on -- a hand-labelled alignment map for evaluating the Align stage.
#
# These 20 are standalone: each is its own prompt group, because each used a
# different instruction.  The CONTROLS below are the other kind -- several
# pairs sharing ONE instruction.
# ---------------------------------------------------------------------------

PAIRS = [
    # ------------------------------------------------------------------ fetch
    dict(
        id="fetch-01",
        category="fetch",
        output_shape="table",
        gold_sections=["2.2 Capabilities Compared", "Table 2"],
        target_prompt=(
            "List the autonomy levels defined in this document. For each level give the "
            "level name, the corresponding paradigm, and the description. Present it as a "
            "markdown table with those three columns, in ascending order of autonomy."
        ),
        output="""| Autonomy Level | Paradigm | Description |
|---|---|---|
| 0 - No Autonomy | Classical Machine Learning | Tackles narrow tasks it was explicitly trained for. |
| 1 - Assistive Autonomy | Generative AI | Handles simple tasks with direct instruction. |
| 2 - Partial Autonomy | Agentic AI: Agent-Oriented Workflow | Manages multi-step tasks with human oversight and intervention. |
| 3 - High Autonomy | Agentic AI: Goal-Oriented Collaboration | Achieves complex tasks with occasional guidance. |
| 4 - Full Autonomy | Agentic AI: Autonomous Decision-Making | Given goals, handles all aspects of tasks independently. |""",
    ),
    dict(
        id="fetch-02",
        category="fetch",
        output_shape="list",
        gold_sections=["2.3 Why Agentic AI?", "3.2.1 Memory Types and Structures"],
        target_prompt=(
            "Find every specific number the document gives about memory or context window "
            "size. For each one, state the figure, what it refers to, and which section it "
            "comes from. Use a bulleted list."
        ),
        output="""- **~4000 words** - the input size ChatGPT 3.5 could handle without access to external data sources (Section 2.3, "Why Agentic AI?").
- **Millions of tokens** - the input size modern foundation models that form part of Agentic AI can handle. The figure is given twice, in Section 2.3 and again in Section 3.2.1, and in Section 2.4 the same growth is described as context windows rising "from a few thousand to millions of tokens".
- **About seven items** - the capacity of human working memory, cited to Miller (1956) as an analogy for the bounded context window (Section 3.2.1, "Memory Types and Structures").

The document gives no figure for retrieval-based memory, describing its capacity only as "virtually unlimited".""",
    ),
    dict(
        id="fetch-03",
        category="fetch",
        output_shape="list",
        gold_sections=["4.2 Agentic AI to AGI?"],
        target_prompt=(
            "Extract the named predictions about when human-level AI or AGI will arrive. "
            "Give one bullet per person with their prediction. Note the year the "
            "predictions were made and the source they are cited to."
        ),
        output="""All four predictions were made as of 2018 and are cited to Ford (2018):

- **Ray Kurzweil** - a 50% chance of human-level AI by 2029.
- **Stuart Russell** - 50 to 70 years.
- **Yann LeCun** - 50 to 100 years.
- **Rodney Brooks** - approximately 180 years.

The document presents this spread as evidence that the timeline for achieving AGI remains uncertain.""",
    ),
    dict(
        id="fetch-04",
        category="fetch",
        output_shape="list",
        gold_sections=["3.1.4 Learning to Reason"],
        target_prompt=(
            "Describe the training pipeline for DeepSeek-R1 exactly as the document "
            "presents it. Number the stages in order and say what each one contributes. "
            "Mention the base model and define any training algorithm that is named."
        ),
        output="""The best-performing DeepSeek variant was built on top of a strong base model, **DeepSeek V3**. Reasoning models generally share the same pre-training phase; what differs is the sequence of stages afterwards. For DeepSeek-R1 (Guo et al., 2025) these are:

1. **Training on a small set of high-quality chain-of-thought examples.** Without this data the model's outputs were significantly less human-readable.
2. **GRPO reinforcement learning**, using a reward function with three components: (i) solution accuracy, assessed via rules or external tools such as code interpreters; (ii) formatting, to ensure output usability; and (iii) language consistency, avoiding mixed-language responses such as Chinese and English - though this component slightly reduced performance.
3. **Supervised fine-tuning** on a mix of self-generated reasoning and non-reasoning data, together with the data used to train DeepSeek V3.
4. **A final human alignment stage** targeting helpfulness and harmlessness.

**GRPO (Group Relative Policy Optimization)** is the reinforcement learning technique introduced in DeepSeekMath (Shao et al., 2024), which curated web data to identify material relevant to mathematical reasoning. GRPO evaluates behavioral policies by averaging output groups rather than computing explicit value functions or models, which are more computationally intensive.

The document also notes that supervised fine-tuning on high-quality instruction data generally precedes reinforcement-learning-based methods, because without it those methods often struggle to improve reasoning meaningfully due to a poorly grounded base behavior.""",
    ),
    dict(
        id="fetch-05",
        category="fetch",
        output_shape="list",
        gold_sections=["3.3 Tools"],
        target_prompt=(
            "The document lists the benefits that tools offer agents. Reproduce that list "
            "exactly, preserving the original numbering and the examples given for each."
        ),
        output="""Tools are external functionalities that can be invoked by an agent. They complement agents and offer several benefits:

(i) **Reducing errors and increasing efficiency** - tools can improve accuracy and speed, such as using a calculator for basic math operations.

(ii) **Functionality and interaction** - tools enable new capabilities for task-solving and engagement; for instance, a web browser allows an agent to perform tasks like online shopping.

(iii) **Interpretability and control** - tools built using classical software can embed rules in a clear and reliable way, enhancing transparency and oversight.""",
    ),
    dict(
        id="fetch-06",
        category="fetch",
        output_shape="prose",
        gold_sections=["5.1 Methodology and Scope", "5.2 Related Surveys"],
        target_prompt=(
            "Which prior surveys did the authors select for close comparison, and on what "
            "criteria? Answer in prose. State how many surveys were assessed in total, how "
            "many were selected, and which of the selected ones mattered most."
        ),
        output="""The authors assessed more than 30 surveys in total. From these they selected seven: five surveys on Agentic AI - Wang et al. (2024), Xi et al. (2025), Acharya et al. (2025), Plaat et al. (2025) and Cheng et al. (2024) - and two on Generative AI, Zhang et al. (2023) and Manduchi et al. (2024).

Four criteria governed the selection: quality, recency, comprehensiveness, and non-overlap with the other chosen surveys. Of the two groups, the authors state plainly that the Agentic AI surveys were significantly more influential in shaping their work, and Section 5.2 discusses only those five in depth.

The selection was the first step of a meta-survey: the authors searched Google Scholar for surveys on "Agentic AI," "LLM agents," and "Generative AI," using the results to identify key papers for forward and backward snowballing, to ensure conceptual completeness, and to synthesize differing viewpoints and identify gaps.""",
    ),
    dict(
        id="fetch-07",
        category="fetch",
        output_shape="prose",
        gold_sections=["3.4.2 Interacting in (Virtual) Worlds"],
        target_prompt=(
            "The document reports a benchmark on which humans dramatically outperform "
            "state-of-the-art language models. Name the benchmark, the models tested, and "
            "the scores. Describe what the benchmark task involves. Keep it to one short "
            "paragraph."
        ),
        output="""On the Workarena++ benchmark (Boisvert et al., 2024), humans score close to 100% while state-of-the-art LLMs including GPT-4o and Llama3 score close to 0%. The benchmark covers web-browser tasks that are relatively simple for people; the example given involves a ticket asking to refill inventory that has fallen below four items, where the system must interpret a chart to identify which items to order and then interact with an ordering page. The document cites this gap as evidence that tasks such as online shopping remain a challenge for AI agents.""",
    ),
    # -------------------------------------------------------------- summarize
    dict(
        id="summ-01",
        category="summarize",
        output_shape="prose",
        gold_sections=["Abstract", "1 Introduction", "6 Conclusion"],
        target_prompt=(
            "Write an executive summary of this paper for a non-technical business "
            "audience. Exactly 150 words or fewer. No jargon, no citations, no bullet "
            "points. Focus on what has changed and why it matters commercially."
        ),
        output="""Agentic AI is the next step beyond the generative AI most people met through ChatGPT. Where generative systems answer a request immediately and in one shot, agentic systems reason through a problem in stages, use external tools, act on their environment, and learn from the feedback they get. That shift makes genuinely new applications possible - multi-step work that previously failed, given only a goal rather than detailed instructions.

The commercial calculus changes too. Smaller, cheaper models that reason can match large ones, so specialised systems become viable even when used infrequently, and computation can be dialled up or down per task to trade cost against quality.

The gains are real but uneven. Agentic AI helps little on translation and only slightly on broad knowledge tests, while costing considerably more to run. Longer task chains also accumulate errors, and the systems are harder to control, specify and oversee.""",
    ),
    dict(
        id="summ-02",
        category="summarize",
        output_shape="list",
        gold_sections=["3.1 Reasoning", "3.1.1", "3.1.2", "3.1.3", "3.1.4"],
        target_prompt=(
            "Summarise the section on reasoning as a nested bullet list. Use one top-level "
            "bullet per subsection, with two to four sub-bullets under each. Keep every "
            "bullet to a single line."
        ),
        output="""- **Decomposition** - breaking a problem into solvable sub-steps
  - Achieved by prompting: chain-of-thought exemplars, "think step-by-step", or explicit least-to-most instructions
  - Structure of the reasoning demonstration matters far more than the content of each step
  - Chain length is more impactful than the difficulty of individual components, though verbosity does not help
  - Hierarchical variants propose high-level steps first, then refine them, often using different models per level
- **Reflection** - examining one's own output to improve it
  - Splits into verification (assessing correctness) and refinement (improving prior output)
  - Verification methods include self-consistency voting, per-step confidence scores, and external oracles such as compilers
  - Refinement methods accumulate prior outputs and feedback into successive prompts, building a "chain of reflections"
  - The capacity of LLMs to reflect usefully without external input has been questioned
- **Planning and Search** - exploring and pruning multiple reasoning paths
  - Tree, Forest and Graph of Thoughts extend chain-of-thought by evaluating partial chains and pruning weak ones
  - These are best understood as fusions of classical search techniques with LLMs
  - Assessing partial solutions is the core difficulty, handled by voting, an LLM evaluator, humans, or task-specific heuristics
  - Such systems need a controller beyond the LLM to hold search state, generate prompts, parse outputs and rank candidates
- **Learning to Reason** - instilling reasoning during training rather than eliciting it by prompt
  - Reasoning ability comes from next-word prediction over data that already contains step-wise reasoning
  - Chain-of-thought data can be bootstrapped: generate, keep the traces that produce correct answers, fine-tune, repeat
  - DeepSeek-R1 illustrates the modern pipeline of curated CoT data, GRPO reinforcement learning, fine-tuning and alignment
  - Human preference training exists but is aimed at helpfulness and safety more than at reasoning""",
    ),
    dict(
        id="summ-03",
        category="summarize",
        output_shape="prose",
        gold_sections=["4.1 Challenges"],
        target_prompt=(
            "Condense the challenges section into a single flowing paragraph. Cover every "
            "challenge named, but do not use a list or name the section. Write it as "
            "continuous prose a reader could quote."
        ),
        output="""The obstacles compound rather than sit side by side: reasoning reduces errors relative to generative AI, yet the length and complexity of agentic tasks raise the risk that errors accumulate across steps, and although step-by-step reasoning in readable text improves interpretability, chain-of-thought traces are not always faithful to the decision process that produced them, while the addition of planning algorithms, external memory and tool use makes the whole system harder to explain than a single model. Agents must operate in dynamic, complex environments, selecting tools and collaborating with other agents, sometimes in parallel, and they must do so without full observability - neither the environment nor the agents' own tools are entirely transparent, since APIs may be opaque. Safety and security risks are higher than for generative AI because agents act in less controlled settings, tool invocation can be exploited, multi-modal agents can be attacked through any modality, and privacy erodes as agents share information with other agents and tools, where even a detail as small as an agent's role can constitute a breach. Evaluation of reliability, task performance and potential harms remains incomplete; agents may pursue their goals through unforeseen or unethical actions; controlling them is difficult because even approval checkpoints require anticipating consequences that are hard to foresee; and resource management grows more demanding as agents dynamically consume arbitrary amounts of information.""",
    ),
    dict(
        id="summ-04",
        category="summarize",
        output_shape="prose",
        gold_sections=["Abstract"],
        target_prompt=(
            "Rewrite the abstract for a general reader with no AI background. Around 80 "
            "words. Plain language, second person where it helps, no technical terms left "
            "undefined."
        ),
        output="""You have probably used an AI that writes text or answers questions on request. This paper is about what comes next: systems that don't just respond but work through a problem, take actions, and adjust as they go. The authors explain how the two differ, what the newer kind makes possible that the older kind could not, and where it still falls short. They close with the open problems, and a warning about what happens if these systems surpass us.""",
    ),
    dict(
        id="summ-05",
        category="summarize",
        output_shape="table",
        gold_sections=["3.5.2 Specifying Multi-Agents"],
        target_prompt=(
            "Summarise the key dimensions of multi-agent systems as a two-column markdown "
            "table: dimension, and what the choice is between. One row per dimension. Keep "
            "the second column under 25 words."
        ),
        output="""| Dimension | The choice |
|---|---|
| Homogeneous vs. Heterogeneous | Exact replicas sharing model and description, versus agents on different models or subject to different instructions. |
| Cooperative vs. Non-cooperative | A shared goal, possibly pursued through argumentative debate, versus independently held goals. |
| Communication structure | Push (unsolicited messages) or pull (explicit requests); centralized through one agent or shared pool, or decentralized. |
| Organization | Flat, or hierarchical - for example workers handling parts of a task with a manager aggregating results. |
| Learning | Independent learning in decentralized systems, versus centrally shared experience to speed collective improvement. |
| Communication content | Primarily text: instructions, goals, state descriptions, action histories and dialogue histories packaged into messages. |""",
    ),
    dict(
        id="summ-06",
        category="summarize",
        output_shape="prose",
        gold_sections=["3.2 Memory", "3.2.1", "3.2.2"],
        target_prompt=(
            "Give me the TL;DR of the memory section in exactly three sentences. Dense, "
            "informative, no hedging."
        ),
        output="""Memory underpins prompt processing, reasoning, personalization and staying current, and comes in four types: parametric memory held in model weights, ephemeral memory bounded by the context window, retrieval-based memory of effectively unlimited capacity, and architectural memory built into the model itself. Parametric memory is treated as fixed during operation because online updates risk catastrophic forgetting or malicious manipulation, which leaves retrieval as the main route to instant learning. Retrieval augmentation reduces hallucination and admits private or post-training data, but introduces its own design problems - chunk size, encoding strategy, and how many chunks to include - and large context windows increasingly make it optional, at the price of higher generation cost.""",
    ),
    # ----------------------------------------------------------------- reason
    dict(
        id="reason-01",
        category="reason",
        output_shape="prose",
        gold_sections=["Table 1", "Table 3", "2.1", "2.3"],
        target_prompt=(
            "This document contains two comparison tables that both contrast GenAI with "
            "Agentic AI. What is the relationship between them - are they redundant? "
            "Explain what each one does that the other does not."
        ),
        output="""They are not redundant. They operate at different levels and do different work in the argument.

Table 1 is definitional. It appears in the section that defines the two terms, and its five rows - reasoning, interaction, execution capability, adaptability, autonomy - are the characteristics that constitute the distinction. Its cells are terse, a few words each, and marked only with a cross or a check. It answers "what is the difference?"

Table 3 is motivational. It appears in the section asking why Agentic AI is needed, and its nine rows are framed as GenAI *limitations* paired with Agentic AI *advantages*. Its cells are full sentences. It answers "what problem does the difference solve?"

The overlap is partial and deliberate. Execution capability appears in both. But Table 3 adds usability, training data, memory, instant learning, errors, transparency, dynamic resource allocation, and cost-efficiency - concerns that are practical and economic rather than definitional. The document is explicit that Table 1's non-foundational rows depend on the foundational two: adaptability, execution capability and autonomy all rest on reasoning and interaction.

There is a third distinction worth noting. Table 3 uses a filled circle alongside the check mark, marking areas where further improvement is still needed - execution capability, training data, errors, and transparency. Table 1 has no such gradation. So Table 3 is also the more honest of the two: it concedes that four of the nine advantages are partial, whereas Table 1's clean crosses and checks imply a sharper break than the document elsewhere defends.""",
    ),
    dict(
        id="reason-02",
        category="reason",
        output_shape="prose",
        gold_sections=["2.3", "Table 3", "4.1 Challenges"],
        target_prompt=(
            "The document claims Agentic AI reduces errors, and also claims it increases "
            "the risk of errors. Are these consistent? Work through what each claim "
            "actually asserts before answering."
        ),
        output="""They are consistent, because the two claims are about different units of analysis.

The reduction claim is per step. In Section 2.3 the argument is that reasoning capabilities reduce errors such as hallucinations - content unfaithful to the input, either contradicting the source (intrinsic) or unverifiable (extrinsic) - and that agents performing self-verification and retrieving external knowledge exhibit lower error rates. Table 3 makes the same claim, with the qualification of a filled circle rather than a check: fewer errors due to step-by-step reasoning and validation, but not a solved problem.

The increase claim is per task. Section 4.1 states that although reasoning reduces errors compared to Generative AI, the complexity and length of tasks in Agentic AI increase the risk of *cumulative* errors across steps. The word doing the work is cumulative.

So the composition is straightforward: a lower per-step error rate applied across many more steps can still yield a higher probability of failure somewhere in the chain. A system that is more reliable at each move but makes twenty moves instead of one may well be less reliable end to end.

Two things follow. First, the claims are compatible but the document never quantifies the trade-off, so it does not establish where the crossover lies - it asserts both directions without saying which dominates at what chain length. Second, this is why failure awareness appears in Section 3.5.3 as an evaluation desideratum in its own right: if errors compound, detecting impending failure matters more than in a single-shot setting, and the document proposes a self-aware failure rate as a metric precisely because per-step accuracy no longer tells you what you need to know.""",
    ),
    dict(
        id="reason-03",
        category="reason",
        output_shape="prose",
        gold_sections=["1 Introduction", "2.3", "Table 3"],
        target_prompt=(
            "A team is deciding whether to adopt Agentic AI for a high-volume machine "
            "translation product. Based only on what this document says, what would you "
            "advise? Give a recommendation, not a survey of considerations."
        ),
        output="""Don't adopt it for the translation itself.

The document is unusually direct on this point: only minor improvements have been observed on translation tasks (Chen et al., 2025). It lists translation alongside social intelligence and MMLU performance as areas where deep reasoning does not deliver the dramatic gains seen in programming, radiology reporting, or the ARC challenge. Agentic AI is explicitly described as not a magic bullet, and translation is one of the named cases.

The cost side settles it. Deep reasoning requires significantly more computation, and the document notes that reasoning models show only a slight edge on MMLU "at the cost of significantly greater computation." For a high-volume product, you would be paying that multiplier on every unit of throughput to buy an improvement the document characterises as minor. The relevant guidance is its closing remark in Section 2.3: fine-tuning GenAI models for specific domains may outperform Agentic AI models that lack domain-specific knowledge, while also incurring lower computational costs. A high-volume translation product is precisely the case where amortising a fine-tune is cheap - the opposite of the infrequent-use scenario the document identifies as favouring small reasoning models.

Where agentic capability might still earn its place is around the translation rather than in it: terminology lookup against a glossary is tool use, and self-verification could gate the small fraction of segments flagged as uncertain. Both are selective applications of reasoning to a minority of traffic, which preserves the cost profile. But that is a quality-assurance layer, not a translation engine, and the document offers no evidence for it in the translation setting specifically - it is an inference from the general tool-use and verification arguments, not a finding.""",
    ),
    dict(
        id="reason-04",
        category="reason",
        output_shape="prose",
        gold_sections=["5.1 Methodology and Scope", "5.2 Related Surveys"],
        target_prompt=(
            "Read the methodology section critically. What limitations does the authors' "
            "own described process impose on the survey's coverage? Be specific about "
            "which choices create which blind spots."
        ),
        output="""Four choices in the described methodology bound what the survey can see.

**The date restriction.** The authors restricted their search to works from 2024 onward, on the assumption that older works were captured in the selected surveys. This inherits the coverage of those five or seven surveys wholesale, including their gaps. Anything from 2020-2023 that all the selected surveys happened to miss is invisible to this one, and the assumption is stated rather than tested.

**Starting from a meta-survey.** Beginning with a search for surveys, then snowballing from them, anchors the whole review to topics that had already attracted a survey by the time of writing. Emerging subfields too new or too small to have been surveyed enter only through the targeted per-subchapter searches, which are described as an addition rather than a systematic sweep.

**Non-overlap as a selection criterion.** Selecting surveys partly for non-overlap with each other optimises for breadth of perspective, but it also means that where several surveys agree, only one of them is represented. Consensus areas are consequently sampled more thinly than contested ones - the reverse of what a reader assessing the weight of evidence would want.

**Venue and source asymmetry.** Forward search focused on citations and publications in NIPS, ICLR and ICML. That is a machine-learning-conference view of a field the survey itself claims spans law, finance, psychology, education, medicine and military applications. Work published in domain venues rather than ML venues is reachable only by chance. In the other direction, the authors admit arXiv preprints and selected blog posts from OpenAI and Huggingface, filtered by "basic quality assessments" that are never specified - so the evidentiary standard varies across the survey without the reader being able to tell where.

A fifth limitation is scope rather than method, and the authors state it plainly: they assume familiarity with foundation models and prompt engineering and deliberately exclude transformer-level technical detail. That is a legitimate boundary, clearly drawn, and unlike the four above it does not create an unacknowledged blind spot.""",
    ),
    dict(
        id="reason-05",
        category="reason",
        output_shape="prose",
        gold_sections=["1 Introduction", "4.2 Agentic AI to AGI?"],
        target_prompt=(
            "Does this paper think scaling alone will get us to AGI? The document does not "
            "state a position outright, so infer it from how the authors present the "
            "evidence. Quote the passages your reading rests on."
        ),
        output="""The authors lean no, but they hold the position loosely and never commit to it in their own voice.

The clearest signal is that they raise the doubt themselves, unprompted, in the introduction: "scaling compute at test-time alone (a key aspect of deep reasoning) may not guarantee progress toward AGI, and important challenges remain, including training data limitations and error accumulation." The hedge - "may not guarantee" - is doing real work, but the sentence is theirs, not a reported view.

Section 4.2 then presents the question as balanced: "Incremental technological advances and scaling of existing Agentic AI systems might be sufficient to achieve AGI. However, progress may stall due to barriers like limited availability of training data (Mok, 2025). Some researchers argue that mere scaling is insufficient, and fundamentally new approaches are required (Bengio and Hu, 2023)." Formally this is even-handed. But the structure is not: the pro-scaling sentence carries no citation, while both sentences against it do, and the "however" places the sceptical case in the position of rebuttal.

The same tilt appears earlier. In Section 2.3 the authors write that the scaling paradigm "may continue to boost AI's capabilities" but "is not necessarily optimal," and immediately give a reason - "there is a significant lack of training data. Data can be expensive to collect - or, in some cases, impossible to obtain." Training data scarcity is raised three separate times across the paper as the binding constraint, and each time it is raised as a limit on scaling specifically.

What stops this being a firm position is the conclusion, which drops the question entirely, and the treatment of the AGI timeline, where the authors' actual claim is about uncertainty rather than direction: they present predictions ranging from 2029 to roughly 180 years as evidence that "the timeline for achieving AGI remains uncertain." A reader would be overstating things to say the paper argues scaling is insufficient. It repeatedly gestures at why scaling might not be enough, declines to argue the case, and settles on uncertainty as the safer claim.""",
    ),
    dict(
        id="reason-06",
        category="reason",
        output_shape="list",
        gold_sections=["1 Introduction", "2.3", "3.4.2", "4.1"],
        target_prompt=(
            "Separate the claims in this document into those backed by quantitative "
            "evidence and those asserted without it. Give the strongest examples of each, "
            "with the numbers where they exist. Then say what that split tells you about "
            "the paper."
        ),
        output="""**Backed by numbers**

- Reasoning models dramatically outperform others on the ARC challenge - the paper's single strongest quantitative claim, with a specific cost-performance figure: tripling spend in monetary terms improved performance from 25% to 32%, a relative gain of over 20%.
- Agents fail at web tasks humans find easy - on Workarena++, humans score close to 100% while GPT-4o and Llama3 score close to 0%. This is the largest effect size in the paper and cuts against its own thesis.
- Small models with reasoning can beat larger ones - a 1B model outperforming an 8B model on MATH-500 given more generations.
- Reasoning models show only a slight edge on MMLU, at significantly greater computational cost.
- Context windows grew from about 4000 words to millions of tokens.

**Asserted without quantitative support**

- That Agentic AI reduces hallucinations. Supported by citation but no error rates are given, and Table 3 marks it as only partially achieved.
- That reasoning improves transparency and interpretability - and, in the same paper, that chain-of-thought "may not always be faithful to the underlying decision process." Neither claim is measured.
- That Agentic AI offers "the potential to reduce biases." Potential is the operative word; no evidence follows.
- The entirety of Section 4.1. Every challenge - cumulative errors, observability, safety, privacy, human alignment, controllability, resource allocation - is asserted and cited, never quantified.
- The cost-efficiency and amortization argument, which is an economic analogy to manufacturing rather than a costed model.

**What the split tells you**

The quantitative evidence clusters in two places: benchmark results on narrow reasoning tasks, and context window sizes. Both are things the field already measures routinely. Everywhere the paper makes its distinctive contribution - the definitions, the autonomy levels, the limitations table, the challenges, the AGI discussion - it is synthesising and asserting rather than measuring. That is the appropriate mode for a survey and the paper is transparent about being one, so this is not a flaw so much as a description of the genre.

It does mean the reader should treat the two halves differently. Where the paper reports numbers it is relaying other people's measurements, and those are checkable. Where it makes its conceptual claims - which is where its value lies - the support is the authors' judgement and the coherence of the framework, and the honest reading of Table 3's four filled circles is that the authors know it.""",
    ),
    dict(
        id="reason-07",
        category="reason",
        output_shape="prose",
        gold_sections=["3.2.2 Retrieval Augmentation", "5.2 Related Surveys", "3.4.2"],
        target_prompt=(
            "The authors classify retrieval augmentation differently from at least one "
            "other survey. Explain the disagreement, the reasoning each side gives, and "
            "what actually turns on it."
        ),
        output="""The disagreement is with Plaat et al. (2025), who treat retrieval augmentation as a form of reasoning. The authors of this survey treat it instead as interaction with a tool, and say so explicitly in Section 5.2, aligning themselves with earlier work such as Lewis et al. (2020) - the RAG paper itself.

Their argument is one of dissociation. If retrieval were constitutive of reasoning, reasoning should require it; it does not. "Basic reasoning forms like chain-of-thought do not require retrieval, and even more advanced reasoning typically only necessitates large context windows." Since you can have reasoning without retrieval, and since retrieval resembles other tool calls - a query issued to an external system, a result returned - it belongs on the interaction side of the paper's two-capability split.

The counter-position is not spelled out here, but the grounds are visible in the survey's own material. Retrieval is not a passive lookup: Asai et al. (2023) make it adaptive through iterative self-reflection, with fine-tuned models emitting retrieval tokens to signal that more information is needed; Yan et al. (2024) classify retrieved knowledge as correct, incorrect or ambiguous, decomposing and recomposing it before it reaches the model. Deciding *whether* to retrieve, and judging what comes back, look a great deal like reasoning steps. On that reading retrieval is interleaved with reasoning rather than sitting beneath it as a service.

What turns on it is mostly architectural framing, and the paper is candid that this is a conceptualisation choice rather than an empirical dispute - it lists the classification among the ways its framework "differs" from Plaat's, not among the ways it corrects them. But the choice is not inert. The authors' own commitments show the strain: they concede in Section 3.4.2 that "tool usage (and access to external memory like databases) could also be viewed as environmental interaction," and defend treating both as internal components on the grounds that tool use is typically a single API call rather than a long perceive-reason-act loop. Adaptive retrieval is exactly the case where that defence weakens, since it *is* a loop.

The practical consequence is where retrieval quality gets optimised. Treat it as a tool and it becomes an engineering problem - chunk size, encoding strategy, number of chunks, the design challenges the paper lists. Treat it as reasoning and it becomes a training problem, folded into what the model learns to do. The survey's own evidence points both ways: it notes that large context windows increasingly let systems forego retrieval entirely, which supports the tool reading, and also that search has been integrated into the reasoning process without labelled data via GRPO (Chen et al., 2025), which supports the other.""",
    ),
]

# ---------------------------------------------------------------------------
# Control sets: several pairs sharing ONE gold prompt, over different slices of
# the document. These are what distinguish a recovered prompt that states the
# rule from one that merely describes the answer it was shown. A prompt that
# says "list the AGI predictions" scores well on the positive input and fails
# the negative one, where the correct behaviour is to say NA.
#
# `span` is a character range into the corpus, so each pair gets a genuinely
# different input without needing a second source document.
# ---------------------------------------------------------------------------

SEC_WHY_AGENTIC = (17298, 24444)     # 2.3  -- has context-window figures
SEC_REFLECTION = (36978, 40463)      # 3.1.2 -- no figures, no predictions
SEC_MEMORY_TYPES = (50754, 53996)    # 3.2.1 -- has memory figures
SEC_TOOLS = (57575, 58187)           # 3.3  -- no figures, no predictions
SEC_AGI = (85284, 87627)             # 4.2  -- has the predictions

NA = "NA"

CONTROLS = [
    dict(
        group="ctl-agi-predictions",
        category="fetch",
        output_shape="list",
        target_prompt=(
            "List every named person in this text together with their prediction for "
            "when human-level AI or AGI will arrive. Give one bullet per person. If "
            "the text contains no such predictions, reply with exactly: NA"
        ),
        members=[
            dict(id="ctl-agi-01", span=SEC_AGI, is_negative=False, output="""\
- **Ray Kurzweil** - a 50% chance of human-level AI by 2029.
- **Stuart Russell** - 50 to 70 years.
- **Yann LeCun** - 50 to 100 years.
- **Rodney Brooks** - approximately 180 years."""),
            dict(id="ctl-agi-02", span=SEC_TOOLS, is_negative=True, output=NA),
            dict(id="ctl-agi-03", span=SEC_REFLECTION, is_negative=True, output=NA),
        ],
    ),
    dict(
        group="ctl-memory-figures",
        category="fetch",
        output_shape="list",
        target_prompt=(
            "Extract every specific number this text gives about memory size or "
            "context window length, stating what each figure refers to. Use a "
            "bulleted list. If the text gives no such numbers, reply with exactly: NA"
        ),
        members=[
            dict(id="ctl-mem-01", span=SEC_WHY_AGENTIC, is_negative=False, output="""\
- **About 4000 words** - the input size ChatGPT 3.5 could handle without access to external data sources.
- **Millions of input tokens** - what modern foundation models forming part of Agentic AI can handle."""),
            dict(id="ctl-mem-02", span=SEC_MEMORY_TYPES, is_negative=False, output="""\
- **About seven items** - the capacity of human working memory, cited to Miller (1956) as an analogy for the bounded context window.
- **Millions of tokens** - what modern model context windows can now hold."""),
            dict(id="ctl-mem-03", span=SEC_REFLECTION, is_negative=True, output=NA),
        ],
    ),
    dict(
        group="ctl-two-sentence",
        category="summarize",
        output_shape="prose",
        target_prompt=(
            "Summarise this section in exactly two sentences. No bullet points, no "
            "heading, no preamble."
        ),
        members=[
            dict(id="ctl-sum-01", span=SEC_TOOLS, is_negative=False, output=(
                "Tools are external functionalities that an agent can invoke to "
                "complement its own capabilities. They offer three benefits: fewer "
                "errors and greater efficiency, new capabilities for task-solving "
                "such as browsing, and better interpretability where classical "
                "software encodes rules explicitly.")),
            dict(id="ctl-sum-02", span=SEC_AGI, is_negative=False, output=(
                "AGI refers to AI that generalises beyond narrow domains to "
                "unfamiliar situations, and Agentic AI may be the next step toward "
                "it, though whether scaling alone suffices is disputed and the "
                "predictions of respected researchers range from 2029 to roughly "
                "180 years. If it arrives the consequences are hard to predict, "
                "with warnings that instrumental convergence could drive systems "
                "toward self-preservation and resource acquisition in ways that "
                "clash with human interests.")),
            dict(id="ctl-sum-03", span=SEC_REFLECTION, is_negative=False, output=(
                "Reflection means examining one's own output in order to improve "
                "it, and splits into verification, which checks whether generated "
                "results are correct, and refinement, which improves them. "
                "Verification methods include self-consistency voting, per-step "
                "confidence scores and external oracles such as compilers, while "
                "refinement accumulates prior outputs and feedback into successive "
                "prompts, though the capacity of LLMs to reflect usefully without "
                "external input has been questioned.")),
        ],
    ),
]


def build():
    corpus = CORPUS.read_text()
    digest = hashlib.sha256(corpus.encode()).hexdigest()
    records = []
    for p in PAIRS:
        records.append({
            "id": p["id"],
            "category": p["category"],
            "input_ref": "data/corpus/agentic-ai-survey.md",
            "input_sha256": digest,
            "target_prompt": p["target_prompt"],
            "output": p["output"],
            "output_shape": p["output_shape"],
            "gold_sections": p["gold_sections"],
            # each standalone pair is its own prompt group
            "prompt_group": p["id"],
            "is_negative": False,
        })

    for ctl in CONTROLS:
        for m in ctl["members"]:
            records.append({
                "id": m["id"],
                "category": ctl["category"],
                "input_ref": "data/corpus/agentic-ai-survey.md",
                "input_sha256": digest,
                "input_span": list(m["span"]),
                "target_prompt": ctl["target_prompt"],
                "output": m["output"],
                "output_shape": "prose" if m["output"] == "NA" else ctl["output_shape"],
                "gold_sections": [],
                "prompt_group": ctl["group"],
                "is_negative": m["is_negative"],
            })
    return records


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches this source; do not write")
    args = ap.parse_args()

    body = "\n".join(json.dumps(r, ensure_ascii=False) for r in build()) + "\n"

    if args.check:
        if not OUT.exists():
            raise SystemExit(f"missing {OUT}")
        if OUT.read_text() != body:
            raise SystemExit(f"{OUT} is stale -- rerun tools/build_pairs.py")
        print(f"ok: {OUT} matches source ({len(build())} pairs)")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    records = build()
    groups = {r["prompt_group"] for r in records}
    controls = sum(1 for c in CONTROLS for _ in c["members"])
    print(f"wrote {OUT} -- {len(records)} pairs in {len(groups)} groups "
          f"({len(PAIRS)} standalone, {controls} in {len(CONTROLS)} control sets)")


if __name__ == "__main__":
    main()
